name: Matthew Yang
description: Explorer and lifelong learner
meta_description: Matthew Yang's personal site

markdown: kramdown
highlighter: pygments
logo: false
paginate: 10
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://m45yang.github.io'
author:         'Matthew Yang'
